package main

import "encoding/json"

func unmarshalSearchStruct(data []byte) ([]interface{}, error) {
	var a []SearchStructElement
	err := json.Unmarshal(data, &a)
	b := make([]interface{}, len(a))
	for i := range a {
		b[i] = a[i]
	}
	return b, err
}

// SearchStructElement is one element in the search structure generated by DartDoc
type SearchStructElement struct {
	Name            string `json:"name"`
	QualifiedName   string `json:"qualifiedName"`
	Href            string `json:"href"`
	Type            string `json:"type"`
	OverriddenDepth int64  `json:"overriddenDepth"`
	EnclosedBy      *struct {
		Name string `json:"name"`
		Type string `json:"type"`
	} `json:"enclosedBy,omitempty"`
}

func unmarshalPubSearch(data []byte) (PubSearch, error) {
	var r PubSearch
	err := json.Unmarshal(data, &r)
	return r, err
}

// PubSearch are the search results from pub.dev
type PubSearch struct {
	Packages []struct {
		Package string `json:"package"`
	} `json:"packages"`
	Next string `json:"next"`
}
